mirrors/urls.py
from django.conf.urls import patterns

urlpatterns = patterns('mirrors.views',
    (r'^$',                     'mirrors', {}, 'mirror-list'),
    (r'^status/$',              'status',  {}, 'mirror-status'),
    (r'^status/json/$',         'status_json',  {}, 'mirror-status-json'),
    (r'^status/tier/(?P<tier>\d+)/$', 'status', {}, 'mirror-status-tier'),
    (r'^status/tier/(?P<tier>\d+)/json/$', 'status_json', {}, 'mirror-status-tier-json'),
    (r'^locations/json/$',      'locations_json',  {}, 'mirror-locations-json'),
    (r'^(?P<name>[\.\-\w]+)/$', 'mirror_details'),
    (r'^(?P<name>[\.\-\w]+)/json/$', 'mirror_details_json'),
)

# vim: set ts=4 sw=4 et:

news/urls.py
from django.conf.urls import patterns
from django.contrib.auth.decorators import permission_required
from .views import (NewsDetailView, NewsListView,
        NewsCreateView, NewsEditView, NewsDeleteView)


urlpatterns = patterns('news.views',
    (r'^$',
        NewsListView.as_view(), {}, 'news-list'),

    (r'^preview/$', 'preview'),
    # old news URLs, permanent redirect view so we don't break all links
    (r'^(?P<object_id>\d+)/$', 'view_redirect'),

    (r'^add/$',
        permission_required('news.add_news')(NewsCreateView.as_view())),
    (r'^(?P<slug>[-\w]+)/$',
        NewsDetailView.as_view()),
    (r'^(?P<slug>[-\w]+)/edit/$',
        permission_required('news.change_news')(NewsEditView.as_view())),
    (r'^(?P<slug>[-\w]+)/delete/$',
        permission_required('news.delete_news')(NewsDeleteView.as_view())),
)

# vim: set ts=4 sw=4 et:

urls.py
from django.conf.urls import include, patterns, url
from django.contrib import admin
from django.contrib.sitemaps import views as sitemap_views

from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView, RedirectView

from feeds import PackageFeed, NewsFeed, ReleaseFeed
import sitemaps

our_sitemaps = {
    'base':           sitemaps.BaseSitemap,
    'news':           sitemaps.NewsSitemap,
    'packages':       sitemaps.PackagesSitemap,
    'package-files':  sitemaps.PackageFilesSitemap,
    'package-groups': sitemaps.PackageGroupsSitemap,
    'split-packages': sitemaps.SplitPackagesSitemap,
    'releases':       sitemaps.ReleasesSitemap,
}

admin.autodiscover()
urlpatterns = []

# Public pages
urlpatterns += patterns('public.views',
    (r'^$', 'index', {}, 'index'),
    (r'^about/$', TemplateView.as_view(template_name='public/about.html'),
        {}, 'page-about'),
# Commented out as not used for BlackArchweb
#    (r'^art/$',   TemplateView.as_view(template_name='public/art.html'),
#        {}, 'page-art'),
#    (r'^svn/$',   TemplateView.as_view(template_name='public/svn.html'),
#        {}, 'page-svn'),
    (r'^developers/$',   'userlist', { 'user_type':'devs' },    'page-devs'),
#    (r'^trustedusers/$', 'userlist', { 'user_type':'tus' },     'page-tus'),
#    (r'^fellows/$',      'userlist', { 'user_type':'fellows' }, 'page-fellows'),
    (r'^donate/$',       'donate',   {}, 'page-donate'),
    (r'^download/$',     'download', {}, 'page-download'),
    (r'^master-keys/$',  'keys',     {}, 'page-keys'),
    (r'^master-keys/json/$', 'keys_json', {}, 'pgp-keys-json'),
)

# Feeds patterns, used below
feeds_patterns = patterns('',
    (r'^$',          'public.views.feeds', {}, 'feeds-list'),
    (r'^news/$',     cache_page(300)(NewsFeed())),
    (r'^packages/$', cache_page(300)(PackageFeed())),
    (r'^packages/(?P<arch>[A-z0-9]+)/$',
        cache_page(300)(PackageFeed())),
    (r'^packages/all/(?P<repo>[A-z0-9\-]+)/$',
        cache_page(300)(PackageFeed())),
    (r'^packages/(?P<arch>[A-z0-9]+)/(?P<repo>[A-z0-9\-]+)/$',
        cache_page(300)(PackageFeed())),
    (r'^releases/$', cache_page(300)(ReleaseFeed())),
)

# Includes and other remaining stuff
urlpatterns += patterns('',
    # cache this static JS resource for 1 week rather than default 5 minutes
    (r'^admin/',     include(admin.site.urls)),
    (r'^devel/',     include('devel.urls')),
    (r'^feeds/',     include(feeds_patterns)),
    (r'^groups/',    include('packages.urls_groups')),
    (r'^mirrorlist/',include('mirrors.urls_mirrorlist')),
    (r'^mirrors/',   include('mirrors.urls')),
    (r'^news/',      include('news.urls')),
    (r'^packages/',  include('packages.urls')),
    (r'^releng/',    include('releng.urls')),
    (r'^todo/',      include('todolists.urls')),
    (r'^visualize/', include('visualize.urls')),
    (r'^opensearch/packages/$', 'packages.views.opensearch',
        {}, 'opensearch-packages'),
    (r'^opensearch/packages/suggest$', 'packages.views.opensearch_suggest',
        {}, 'opensearch-packages-suggest'),
)

# Retro home page views
urlpatterns += patterns('retro.views',
    (r'^retro/(?P<year>[0-9]{4})/$', 'retro_homepage', {}, 'retro-homepage'),
)

# Sitemaps
urlpatterns += patterns('',
    (r'^sitemap.xml$',
        cache_page(1800)(sitemap_views.index),
        {'sitemaps': our_sitemaps, 'sitemap_url_name': 'sitemaps'}),
    (r'^sitemap-(?P<section>.+)\.xml$',
        cache_page(1800)(sitemap_views.sitemap),
        {'sitemaps': our_sitemaps}, 'sitemaps'),
)

# Authentication / Admin
urlpatterns += patterns('django.contrib.auth.views',
    (r'^login/$',           'login',  {
        'template_name': 'registration/login.html'}),
    (r'^logout/$',          'logout', {
        'template_name': 'registration/logout.html'}),
)

# Redirects for older known pages we see in the logs
legacy_urls = (
    ('^about.php',     '/about/'),
    ('^changelog.php', '/packages/?sort=-last_update'),
    ('^devs.php',      '/developers/'),
    ('^donations.php', '/donate/'),
    ('^download.php',  '/download/'),
    ('^index.php',     '/'),
    ('^logos.php',     '/art/'),
    ('^news.php',      '/news/'),
    ('^packages.php',  '/packages/'),
    ('^people.php',    '/developers/'),
    ('^todolists/$',   '/todo/'),

    ('^docs/en/guide/install/arch-install-guide.html',
        'https://wiki.archlinux.org/index.php/Installation_Guide'),
    ('^docs/en/',
        'https://wiki.archlinux.org/'),
    ('^docs/',
        'https://wiki.archlinux.org/'),
)

urlpatterns += [url(old_url, RedirectView.as_view(url=new_url))
        for old_url, new_url in legacy_urls]


def show_urls(urllist=urlpatterns, depth=0):
    for entry in urllist:
        print "  " * depth, entry.regex.pattern
        if hasattr(entry, 'url_patterns'):
            show_urls(entry.url_patterns, depth + 1)

# vim: set ts=4 sw=4 et:

mirrors/models.py
import socket
from urlparse import urlparse

from django.core.exceptions import ValidationError
from django.db import models
from django.db.models.signals import pre_save
from django_countries import CountryField

from .fields import IPNetworkField
from main.utils import set_created_field


class Mirror(models.Model):
    TIER_CHOICES = (
        (0, 'Tier 0'),
        (1, 'Tier 1'),
        (2, 'Tier 2'),
        (-1, 'Untiered'),
    )

    name = models.CharField(max_length=255, unique=True)
    tier = models.SmallIntegerField(default=2, choices=TIER_CHOICES)
    upstream = models.ForeignKey('self', null=True, on_delete=models.SET_NULL)
    admin_email = models.EmailField(max_length=255, blank=True)
    alternate_email = models.EmailField(max_length=255, blank=True)
    public = models.BooleanField(default=True)
    active = models.BooleanField(default=True)
    isos = models.BooleanField("ISOs", default=True)
    rsync_user = models.CharField(max_length=50, blank=True, default='')
    rsync_password = models.CharField(max_length=50, blank=True, default='')
    notes = models.TextField(blank=True)
    created = models.DateTimeField(editable=False)

    class Meta:
        ordering = ('name',)

    def __unicode__(self):
        return self.name

    def downstream(self):
        return Mirror.objects.filter(upstream=self).order_by('name')

    def get_absolute_url(self):
        return '/mirrors/%s/' % self.name


class MirrorProtocol(models.Model):
    protocol = models.CharField(max_length=10, unique=True)
    is_download = models.BooleanField(default=True,
            help_text="Is protocol useful for end-users, e.g. HTTP")
    default = models.BooleanField(default=True,
            help_text="Included by default when building mirror list?")
    created = models.DateTimeField(editable=False)

    def __unicode__(self):
        return self.protocol

    class Meta:
        ordering = ('protocol',)


class MirrorUrl(models.Model):
    url = models.CharField("URL", max_length=255, unique=True)
    protocol = models.ForeignKey(MirrorProtocol, related_name="urls",
            editable=False, on_delete=models.PROTECT)
    mirror = models.ForeignKey(Mirror, related_name="urls")
    country = CountryField(blank=True, db_index=True)
    has_ipv4 = models.BooleanField("IPv4 capable", default=True,
            editable=False)
    has_ipv6 = models.BooleanField("IPv6 capable", default=False,
            editable=False)
    created = models.DateTimeField(editable=False)
    active = models.BooleanField(default=True)

    def address_families(self):
        hostname = urlparse(self.url).hostname
        info = socket.getaddrinfo(hostname, None, 0, socket.SOCK_STREAM)
        families = [x[0] for x in info]
        return families

    @property
    def hostname(self):
        return urlparse(self.url).hostname

    def clean(self):
        try:
            # Auto-map the protocol field by looking at the URL
            protocol = urlparse(self.url).scheme
            self.protocol = MirrorProtocol.objects.get(protocol=protocol)
        except Exception as e:
            raise ValidationError(e)
        try:
            families = self.address_families()
            self.has_ipv4 = socket.AF_INET in families
            self.has_ipv6 = socket.AF_INET6 in families
        except socket.error:
            # We don't fail in this case; we'll just set both to False
            self.has_ipv4 = False
            self.has_ipv6 = False

    def __unicode__(self):
        return self.url

    class Meta:
        verbose_name = 'mirror URL'


class MirrorRsync(models.Model):
    # max length is 40 chars for full-form IPv6 addr + subnet
    ip = IPNetworkField("IP")
    mirror = models.ForeignKey(Mirror, related_name="rsync_ips")
    created = models.DateTimeField(editable=False)

    def __unicode__(self):
        return self.ip

    class Meta:
        verbose_name = 'mirror rsync IP'
        ordering = ('ip',)


class CheckLocation(models.Model):
    hostname = models.CharField(max_length=255)
    source_ip = models.GenericIPAddressField(verbose_name='source IP',
            unpack_ipv4=True, unique=True)
    country = CountryField()
    created = models.DateTimeField(editable=False)

    class Meta:
        ordering = ('hostname', 'source_ip')

    def __unicode__(self):
        return self.hostname

    @property
    def family(self):
        info = socket.getaddrinfo(self.source_ip, None, 0, 0, 0,
                socket.AI_NUMERICHOST)
        families = [x[0] for x in info]
        return families[0]

    @property
    def ip_version(self):
        '''Returns integer '4' or '6'.'''
        if self.family == socket.AF_INET6:
            return 6
        if self.family == socket.AF_INET:
            return 4
        return None


class MirrorLog(models.Model):
    url = models.ForeignKey(MirrorUrl, related_name="logs")
    location = models.ForeignKey(CheckLocation, related_name="logs", null=True)
    check_time = models.DateTimeField(db_index=True)
    last_sync = models.DateTimeField(null=True)
    duration = models.FloatField(null=True)
    is_success = models.BooleanField(default=True)
    error = models.TextField(blank=True, default='')

    def __unicode__(self):
        return "Check of %s at %s" % (self.url.url, self.check_time)

    class Meta:
        verbose_name = 'mirror check log'
        get_latest_by = 'check_time'


for model in (Mirror, MirrorProtocol, MirrorUrl, MirrorRsync, CheckLocation):
    pre_save.connect(set_created_field, sender=model,
            dispatch_uid="mirrors.models")

# vim: set ts=4 sw=4 et:

templates/mirrors/error_table.html
{% load cycle from future %}
{% load flags mirror_status %}
<table id="errorlog_mirrors" class="results">
    <thead>
        <tr>
            <th>Mirror URL</th>
            <th>Protocol</th>
            <th>Country</th>
            <th>Error Message</th>
            <th>Last Occurred</th>
            <th>Occurrences (last {{ cutoff|hours }})</th>
        </tr>
    </thead>
    <tbody>
        {% for log in error_logs %}<tr class="{% cycle 'odd' 'even' %}">
            <td>{{ log.url__url }}</td>
            <td>{{ log.url__protocol__protocol }}</td>
            <td class="country">{% country_flag log.country %}{{ log.country.name }}</td>
            <td class="wrap">{{ log.error|linebreaksbr }}</td>
            <td>{{ log.last_occurred|date:'Y-m-d H:i' }}</td>
            <td>{{ log.error_count }}</td>
        </tr>{% endfor %}
    </tbody>
</table>

templates/mirrors/mirror_details.html
{% extends "base.html" %}
{% load cycle from future %}
{% load static from staticfiles %}
{% load mirror_status %}
{% load flags %}
{% load admin_urls %}

{% block title %}BlackArch - {{ mirror.name }} - Mirror Details{% endblock %}

{% block head %}<link rel="stylesheet" type="text/css" href="{% static "flags/fam.css" %}" media="screen, projection" />{% endblock %}

{% block content %}
<div class="box">
    <h2>Mirror Details: {{ mirror.name }}</h2>

    {% if perms.mirrors.change_mirror %}
    <ul class="admin-actions">
        <li><a href="{% url 'admin:mirrors_mirror_change' mirror.pk %}" title="Edit mirror">Edit Mirror</a></li>
    </ul>
    {% endif %}

    <table class="compact">
        <tr>
            <th>Name:</th>
            <td>{{ mirror.name }}</td>
        </tr>
        <tr>
            <th>Tier:</th>
            <td>{{ mirror.get_tier_display }}</td>
        </tr>
        <tr>
            <th>Has ISOs:</th>
            <td>{{ mirror.isos|yesno|capfirst }}</td>
        </tr>
        {% if user.is_authenticated %}
        <tr>
            <th>Public:</th>
            <td>{{ mirror.public|yesno|capfirst }}</td>
        </tr>
        <tr>
            <th>Active:</th>
            <td>{{ mirror.active|yesno|capfirst }}</td>
        </tr>
        <tr>
            <th>Rsync IPs:</th>
            <td class="wrap">{{mirror.rsync_ips.all|join:', '}}</td>
        </tr>
        <tr>
            <th>Admin Email:</th>
            <td>{% if mirror.admin_email %}<a href="mailto:{{ mirror.admin_email }}">{{ mirror.admin_email }}</a>{% else %}None{% endif %}</td>
        </tr>
        <tr>
            <th>Alternate Email:</th>
            <td>{% if mirror.alternate_email %}<a href="mailto:{{ mirror.alternate_email }}">{{ mirror.alternate_email }}</a>{% else %}None{% endif %}</td>
        </tr>
        <tr>
            <th>Notes:</th>
            <td>{{ mirror.notes|linebreaks }}</td>
        </tr>
        <tr>
            <th>Upstream:</th>
            <td>{% if mirror.upstream %}
                <a href="{{ mirror.upstream.get_absolute_url }}"
                    title="Mirror details for {{ mirror.upstream.name }}">{{ mirror.upstream.name }}</a>
                {% else %}None{% endif %}</td>
        </tr>
        <tr>
            <th>Downstream:</th>
            {% with mirror.downstream as ds_mirrors %}
            <td>{% if ds_mirrors %}
                {% for ds in ds_mirrors %}
                <a href="{{ ds.get_absolute_url }}"
                    title="Mirror details for {{ ds.name }}">{{ ds.name }}</a>
                {% if not ds.active %}<span class="testing-dep">(inactive)</span>{% endif %}
                {% if not ds.public %}<span class="testing-dep">(private)</span>{% endif %}
                <br/>
                {% endfor %}
                {% else %}None{% endif %}</td>
            {% endwith %}
        </tr>
        {% endif %}
    </table>

    <h3>Available URLs</h3>

    <table id="available_urls" class="results">
        <thead>
            <tr>
                <th>Mirror URL</th>
                <th>Protocol</th>
                <th>Country</th>
                <th>IPv4</th>
                <th>IPv6</th>
                <th>Last Sync</th>
                <th>Completion %</th>
                <th>μ Delay (hh:mm)</th>
                <th>μ Duration (secs)</th>
                <th>σ Duration (secs)</th>
                <th>Mirror Score</th>
            </tr>
        </thead>
        <tbody>
            {% for m_url in urls %}
            <tr class="{% cycle 'odd' 'even' %}">
                <td>{% if m_url.protocol.is_download %}<a href="{{ m_url.url }}">{{ m_url.url }}</a>{% else %}{{ m_url.url }}{% endif %}</td>
                <td>{{ m_url.protocol }}</td>
                <td class="country">{% country_flag m_url.country %}{{ m_url.country.name }}</td>
                <td>{{ m_url.has_ipv4|yesno|capfirst }}</td>
                <td>{{ m_url.has_ipv6|yesno|capfirst }}</td>
                <td>{{ m_url.last_sync|date:'Y-m-d H:i'|default:'unknown' }}</td>
                <td>{{ m_url.completion_pct|percentage:1 }}</td>
                <td>{{ m_url.delay|duration|default:'unknown' }}</td>
                <td>{{ m_url.duration_avg|floatvalue:2 }}</td>
                <td>{{ m_url.duration_stddev|floatvalue:2 }}</td>
                <td>{{ m_url.score|floatvalue:1|default:'∞' }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <h3>Error Log</h3>
    {% include "mirrors/error_table.html" %}
</div>

<div class="box">
    <h2>Mirror Status Charts</h2>

    <p>Periodic checks of the mirrors are done from various geographic
    locations, IP addresses, and using IPv4 or IPv6. These results are
    summarized in graphical form below.</p>

    <div id="charts-container"></div>
</div>
{% endblock %}

{% block script_block %}
{% load cdn %}{% jquery %}{% jquery_tablesorter %}
<script type="text/javascript" src="{% static "d3-3.0.6.min.js" %}"></script>
<script type="text/javascript" src="{% static "archweb.js" %}"></script>
<script type="text/javascript" src="{% static "mirror_status.js" %}"></script>
<script type="text/javascript">
$(document).ready(function() {
    $("#available_urls:has(tbody tr)").tablesorter(
        {widgets: ['zebra'], sortList: [[1,0], [2,0]],
        headers: { 8: { sorter: 'mostlydigit' }, 9: { sorter: 'mostlydigit' }, 10: { sorter: 'mostlydigit' } } });
});
$(document).ready(function() {
    draw_graphs("/mirrors/locations/json/", "./json/", "#charts-container");
});
</script>
{% endblock %}

templates/mirrors/mirrorlist_generate.html
{% extends "base.html" %}
{% load package_extras %}
{% block title %}BlackArch - Pacman Mirrorlist Generator{% endblock %}

{% block content %}
<div id="mirrorlist-gen" class="box">

    <h2>Pacman Mirrorlist Generator</h2>

    <p>This page generates the most up-to-date mirrorlist possible for Arch
    Linux. The data used here comes straight from the developers' internal
    mirror database used to track mirror availability and tiering. There are
    two main options: get a mirrorlist with every available mirror, or get a
    mirrorlist tailored to your geography.</p>

    <h3>Mirrorlist with all available mirrors</h3>

    <p>An up-to-date mirrorlist is available containing all currently active
    mirrors, optionally filtering by protocol. These URLs requires no GET or
    POST parameters so they can be fetched from the command line if desired.<p>

    <ul>
        <li><a href="all/">All mirrors</a></li>
        <li><a href="all/http/">All mirrors, HTTP only</a></li>
        <li><a href="all/https/">All mirrors, HTTPS only</a></li>
    </ul>

    <h3>Customized by country mirrorlist</h3>

    <p>The following form can generate a custom up-to-date
    <a href="https://wiki.archlinux.org/index.php/Pacman"
        title="ArchWiki: Pacman">pacman</a> mirrorlist based on geography and
    desired protocol(s).  Simply replace the contents of
    <code>/etc/pacman.d/mirrorlist</code> with your generated list.
    Additionally, the mirror status data can be incorporated into the generated
    mirror list and used to pre-order the mirrors.</p>

    <form id="list-generator" method="get">
        {{ mirrorlist_form.as_div }}
        <p><label></label> <input type="submit" value="Generate List" /></p>
    </form>
</div>
{% endblock %}

templates/mirrors/mirrors.html
{% extends "base.html" %}
{% load cycle from future %}
{% load static from staticfiles %}
{% block title %}BlackArch - Mirror Overview{% endblock %}

{% block content %}
<div id="dev-mirrorlist" class="box">
    <h2>Mirror Overview</h2>
    <table class="results">
        <thead>
            <tr>
                <th>Server</th>
                <th>Tier</th>
                <th>ISOs</th>
                <th>Protocols</th>
                {% if user.is_authenticated %}
                <th>Public</th>
                <th>Active</th>
                <th>Admin Email</th>
                <th>Notes</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for mirror in mirror_list %}
            <tr class="{% cycle 'odd' 'even' %}">
                <td><a href="{{ mirror.get_absolute_url }}"
                        title="Mirror details for {{ mirror.name }}">{{ mirror.name }}</a></td>
                <td>{{ mirror.get_tier_display }}</td>
                <td>{{ mirror.isos|yesno|capfirst }}</td>
                <td class="wrap">{{ mirror.protocols|join:", " }}</td>
                {% if user.is_authenticated %}
                <td>{{ mirror.public|yesno|capfirst }}</td>
                <td>{{ mirror.active|yesno|capfirst }}</td>
                <td>{{ mirror.admin_email }}</td>
                <td class="wrap">{{ mirror.notes|linebreaks }}</td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% load cdn %}{% jquery %}{% jquery_tablesorter %}
<script type="text/javascript" src="{% static "archweb.js" %}"></script>
<script type="text/javascript">
$(document).ready(function() {
    $(".results").tablesorter({widgets: ['zebra'], sortList: [[1,0], [0,0]]});
});
</script>
{% endblock %}

templates/mirrors/status.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% load mirror_status %}
{% load flags %}

{% block title %}BlackArch - Mirror Status{% if tier != None %} - Tier {{ tier }}{% endif %}{% endblock %}

{% block head %}<link rel="stylesheet" type="text/css" href="{% static "flags/fam.css" %}" media="screen, projection" />{% endblock %}

{% block content %}
<div id="mirrorstatus" class="box">
    <h2>Mirror Status{% if tier != None %} - Tier {{ tier }}{% endif %}</h2>
    <p>This page reports the status of all known, public, and active BlackArch
    mirrors. All data on this page reflects the status of the mirrors within
    the <em>last {{ cutoff|hours }}</em>. All listed times are UTC. The check script runs
    on a regular basis and polls for the <tt>lastsync</tt> file in the root of
    our repository layout. This file is regularly updated on the central
    repository, so checking the value within allows one to see if the mirror
    has synced recently. This page contains several pieces of information about
    each mirror.</p>
    <ul>
        <li><em>Mirror URL:</em> Mirrors are checked on a per-URL basis. All
        available URLs and protocols for each known mirror are listed.</li>
        <li><em>Completion %:</em> The number of mirror checks that have
        successfully connected and disconnected from the given URL. If this is
        below 100%, the mirror may be unreliable.</li>
        <li><em>μ Delay:</em> The calculated average mirroring delay; e.g. the
        mean value of <tt>last check − last sync</tt> for each check of
        this mirror URL. Due to the timing of mirror checks, any value under
        one hour should be viewed as ideal.</li>
        <li><em>μ Duration:</em> The average (mean) time it took to connect and
        retrieve the <tt>lastsync</tt> file from the given URL. Note that this
        connection time is from the location of the Arch server; your geography
        may product different results.</li>
        <li><em>σ Duration:</em> The standard deviation of the connect and
        retrieval time. A high standard deviation can indicate an unstable or
        overloaded mirror.</li>
        <li><em>Mirror Score:</em> A very rough calculation for ranking
        mirrors. It is currently calculated as <tt>(hours delay + average
            duration + standard deviation) / completion percentage</tt>. Lower
        is better.</li>
    </ul>
    <p>The final table on this page is an error log, which shows any errors
    that occurred while contacting mirrors. This only shows errors that
    occurred within the last {{ cutoff|hours }}.</p>
    <ul>
        <li><a href="#outofsync">Out of Sync Mirrors</a></li>
        <li><a href="#successful">Successfully Syncing Mirrors</a></li>
        <li><a href="#errorlog">Mirror Syncing Error Log</a></li>
    </ul>

    <p>The last mirror check ran at {{ last_check|date:'Y-m-d H:i' }} UTC.
    Checks have ran {{ num_checks }} times in the last {{ cutoff|hours }} at
    an average interval of {{ check_frequency|duration }} (hh:mm).</p>

    <p>This data is also available in <a href="json/">JSON format</a>. The
    units of all time/duration values are in seconds; date/time values are
    UTC.</p>

    <a name="outofsync" id="outofsync"></a>
    <h3>Out of Sync Mirrors</h3>
    {% with urls=bad_urls  table_id='outofsync_mirrors' %}
    {% include "mirrors/status_table.html" %}
    {% endwith %}

    <a name="successful" id="successful"></a>
    <h3>Successfully Syncing Mirrors</h3>
    {% with urls=good_urls table_id='successful_mirrors' %}
    {% include "mirrors/status_table.html" %}
    {% endwith %}

    <a name="errorlog" id="errorlog"></a>
    <h3>Mirror Syncing Error Log</h3>
    {% include "mirrors/error_table.html" %}
</div>
{% endblock %}

{% block script_block %}
{% load cdn %}{% jquery %}{% jquery_tablesorter %}
<script type="text/javascript" src="{% static "archweb.js" %}"></script>
<script type="text/javascript">
$(document).ready(function() {
    var headers = { 4: { sorter: 'duration' }, 5: { sorter: 'mostlydigit' }, 6: { sorter: 'mostlydigit' }, 7: { sorter: 'mostlydigit' } };
    $("#outofsync_mirrors:has(tbody tr)").tablesorter(
        {widgets: ['zebra'], sortList: [[4,0]], headers: headers });
    $("#successful_mirrors:has(tbody tr)").tablesorter(
        {widgets: ['zebra'], sortList: [[7,0]], headers: headers });
    $("#errorlog_mirrors:has(tbody tr)").tablesorter(
        {widgets: ['zebra'], sortList: [[4,1], [5,1]]});
});
</script>
{% endblock %}

templates/mirrors/status_table.html
{% load cycle from future %}
{% load flags mirror_status %}
<table id="{{ table_id }}" class="results">
    <thead>
        <tr>
            <th>Mirror URL</th>
            <th>Protocol</th>
            <th>Country</th>
            <th>Completion %</th>
            <th>μ Delay (hh:mm)</th>
            <th>μ Duration (secs)</th>
            <th>σ Duration (secs)</th>
            <th>Mirror Score</th>
        </tr>
    </thead>
    <tbody>
        {% for m_url in urls %}<tr class="{% cycle 'odd' 'even' %}">
            <td>{{ m_url.url }}</td>
            <td>{{ m_url.protocol }}</td>
            <td class="country">{% country_flag m_url.country %}{{ m_url.country.name }}</td>
            <td>{{ m_url.completion_pct|percentage:1 }}</td>
            <td>{{ m_url.delay|duration|default:'unknown' }}</td>
            <td>{{ m_url.duration_avg|floatvalue:2 }}</td>
            <td>{{ m_url.duration_stddev|floatvalue:2 }}</td>
            <td>{{ m_url.score|floatvalue:1|default:'∞' }}</td>
        </tr>{% endfor %}
    </tbody>
</table>