news/urls.py
from django.conf.urls import patterns
from django.contrib.auth.decorators import permission_required
from .views import (NewsDetailView, NewsListView,
        NewsCreateView, NewsEditView, NewsDeleteView)


urlpatterns = patterns('news.views',
    (r'^$',
        NewsListView.as_view(), {}, 'news-list'),

    (r'^preview/$', 'preview'),
    # old news URLs, permanent redirect view so we don't break all links
    (r'^(?P<object_id>\d+)/$', 'view_redirect'),

    (r'^add/$',
        permission_required('news.add_news')(NewsCreateView.as_view())),
    (r'^(?P<slug>[-\w]+)/$',
        NewsDetailView.as_view()),
    (r'^(?P<slug>[-\w]+)/edit/$',
        permission_required('news.change_news')(NewsEditView.as_view())),
    (r'^(?P<slug>[-\w]+)/delete/$',
        permission_required('news.delete_news')(NewsDeleteView.as_view())),
)

# vim: set ts=4 sw=4 et:

urls.py
from django.conf.urls import include, patterns, url
from django.contrib import admin
from django.contrib.sitemaps import views as sitemap_views

from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView, RedirectView

from feeds import PackageFeed, NewsFeed, ReleaseFeed
import sitemaps

our_sitemaps = {
    'base':           sitemaps.BaseSitemap,
    'news':           sitemaps.NewsSitemap,
    'packages':       sitemaps.PackagesSitemap,
    'package-files':  sitemaps.PackageFilesSitemap,
    'package-groups': sitemaps.PackageGroupsSitemap,
    'split-packages': sitemaps.SplitPackagesSitemap,
    'releases':       sitemaps.ReleasesSitemap,
}

admin.autodiscover()
urlpatterns = []

# Public pages
urlpatterns += patterns('public.views',
    (r'^$', 'index', {}, 'index'),
    (r'^about/$', TemplateView.as_view(template_name='public/about.html'),
        {}, 'page-about'),
# Commented out as not used for BlackArchweb
#    (r'^art/$',   TemplateView.as_view(template_name='public/art.html'),
#        {}, 'page-art'),
#    (r'^svn/$',   TemplateView.as_view(template_name='public/svn.html'),
#        {}, 'page-svn'),
    (r'^developers/$',   'userlist', { 'user_type':'devs' },    'page-devs'),
#    (r'^trustedusers/$', 'userlist', { 'user_type':'tus' },     'page-tus'),
#    (r'^fellows/$',      'userlist', { 'user_type':'fellows' }, 'page-fellows'),
    (r'^donate/$',       'donate',   {}, 'page-donate'),
    (r'^download/$',     'download', {}, 'page-download'),
    (r'^master-keys/$',  'keys',     {}, 'page-keys'),
    (r'^master-keys/json/$', 'keys_json', {}, 'pgp-keys-json'),
)

# Feeds patterns, used below
feeds_patterns = patterns('',
    (r'^$',          'public.views.feeds', {}, 'feeds-list'),
    (r'^news/$',     cache_page(300)(NewsFeed())),
    (r'^packages/$', cache_page(300)(PackageFeed())),
    (r'^packages/(?P<arch>[A-z0-9]+)/$',
        cache_page(300)(PackageFeed())),
    (r'^packages/all/(?P<repo>[A-z0-9\-]+)/$',
        cache_page(300)(PackageFeed())),
    (r'^packages/(?P<arch>[A-z0-9]+)/(?P<repo>[A-z0-9\-]+)/$',
        cache_page(300)(PackageFeed())),
    (r'^releases/$', cache_page(300)(ReleaseFeed())),
)

# Includes and other remaining stuff
urlpatterns += patterns('',
    # cache this static JS resource for 1 week rather than default 5 minutes
    (r'^admin/',     include(admin.site.urls)),
    (r'^devel/',     include('devel.urls')),
    (r'^feeds/',     include(feeds_patterns)),
    (r'^groups/',    include('packages.urls_groups')),
    (r'^mirrorlist/',include('mirrors.urls_mirrorlist')),
    (r'^mirrors/',   include('mirrors.urls')),
    (r'^news/',      include('news.urls')),
    (r'^packages/',  include('packages.urls')),
    (r'^releng/',    include('releng.urls')),
    (r'^todo/',      include('todolists.urls')),
    (r'^visualize/', include('visualize.urls')),
    (r'^opensearch/packages/$', 'packages.views.opensearch',
        {}, 'opensearch-packages'),
    (r'^opensearch/packages/suggest$', 'packages.views.opensearch_suggest',
        {}, 'opensearch-packages-suggest'),
)

# Retro home page views
urlpatterns += patterns('retro.views',
    (r'^retro/(?P<year>[0-9]{4})/$', 'retro_homepage', {}, 'retro-homepage'),
)

# Sitemaps
urlpatterns += patterns('',
    (r'^sitemap.xml$',
        cache_page(1800)(sitemap_views.index),
        {'sitemaps': our_sitemaps, 'sitemap_url_name': 'sitemaps'}),
    (r'^sitemap-(?P<section>.+)\.xml$',
        cache_page(1800)(sitemap_views.sitemap),
        {'sitemaps': our_sitemaps}, 'sitemaps'),
)

# Authentication / Admin
urlpatterns += patterns('django.contrib.auth.views',
    (r'^login/$',           'login',  {
        'template_name': 'registration/login.html'}),
    (r'^logout/$',          'logout', {
        'template_name': 'registration/logout.html'}),
)

# Redirects for older known pages we see in the logs
legacy_urls = (
    ('^about.php',     '/about/'),
    ('^changelog.php', '/packages/?sort=-last_update'),
    ('^devs.php',      '/developers/'),
    ('^donations.php', '/donate/'),
    ('^download.php',  '/download/'),
    ('^index.php',     '/'),
    ('^logos.php',     '/art/'),
    ('^news.php',      '/news/'),
    ('^packages.php',  '/packages/'),
    ('^people.php',    '/developers/'),
    ('^todolists/$',   '/todo/'),

    ('^docs/en/guide/install/arch-install-guide.html',
        'https://wiki.archlinux.org/index.php/Installation_Guide'),
    ('^docs/en/',
        'https://wiki.archlinux.org/'),
    ('^docs/',
        'https://wiki.archlinux.org/'),
)

urlpatterns += [url(old_url, RedirectView.as_view(url=new_url))
        for old_url, new_url in legacy_urls]


def show_urls(urllist=urlpatterns, depth=0):
    for entry in urllist:
        print "  " * depth, entry.regex.pattern
        if hasattr(entry, 'url_patterns'):
            show_urls(entry.url_patterns, depth + 1)

# vim: set ts=4 sw=4 et:

news/models.py
import markdown

from django.db import models
from django.contrib.auth.models import User
from django.contrib.sites.models import Site
from django.utils.safestring import mark_safe
from django.utils.timezone import now


class News(models.Model):
    slug = models.SlugField(max_length=255, unique=True)
    author = models.ForeignKey(User, related_name='news_author',
            on_delete=models.PROTECT)
    postdate = models.DateTimeField("post date", db_index=True)
    last_modified = models.DateTimeField(editable=False, db_index=True)
    title = models.CharField(max_length=255)
    guid = models.CharField(max_length=255, editable=False)
    content = models.TextField()
    safe_mode = models.BooleanField(default=True)

    def get_absolute_url(self):
        return '/news/%s/' % self.slug

    def html(self):
        return mark_safe(markdown.markdown(
            self.content, safe_mode=self.safe_mode, enable_attributes=False))

    def __unicode__(self):
        return self.title

    class Meta:
        db_table = 'news'
        verbose_name_plural = 'news'
        get_latest_by = 'postdate'
        ordering = ('-postdate',)


def set_news_fields(sender, **kwargs):
    news = kwargs['instance']
    current_time = now()
    news.last_modified = current_time
    if not news.postdate:
        news.postdate = current_time
        # http://diveintomark.org/archives/2004/05/28/howto-atom-id
        news.guid = 'tag:%s,%s:%s' % (Site.objects.get_current(),
                current_time.strftime('%Y-%m-%d'), news.get_absolute_url())

# connect signals needed to keep cache in line with reality
from main.utils import refresh_latest
from django.db.models.signals import pre_save, post_save

post_save.connect(refresh_latest, sender=News,
        dispatch_uid="news.models")
pre_save.connect(set_news_fields, sender=News,
        dispatch_uid="news.models")

# vim: set ts=4 sw=4 et:

news/views.py
import markdown

from django import forms
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.views.decorators.http import require_POST
from django.views.generic import (DetailView, ListView,
        CreateView, UpdateView, DeleteView)

from .models import News
from main.utils import find_unique_slug


class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        exclude = ('id', 'slug', 'author', 'postdate', 'safe_mode')


class NewsDetailView(DetailView):
    queryset = News.objects.all().select_related('author')
    template_name = "news/view.html"


class NewsListView(ListView):
    queryset = News.objects.all().select_related('author').defer('content')
    template_name = "news/list.html"
    paginate_by = 50


class NewsCreateView(CreateView):
    model = News
    form_class = NewsForm
    template_name = "news/add.html"

    def form_valid(self, form):
        # special logic, we auto-fill the author and slug fields
        newsitem = form.save(commit=False)
        newsitem.author = self.request.user
        newsitem.slug = find_unique_slug(News, newsitem.title)
        newsitem.save()
        return super(NewsCreateView, self).form_valid(form)


class NewsEditView(UpdateView):
    model = News
    form_class = NewsForm
    template_name = "news/add.html"


class NewsDeleteView(DeleteView):
    model = News
    template_name = "news/delete.html"
    success_url = "/news/"


def view_redirect(request, object_id):
    newsitem = get_object_or_404(News, pk=object_id)
    return redirect(newsitem, permanent=True)


@require_POST
def preview(request):
    data = request.POST.get('data', '')
    markup = markdown.markdown(data, safe_mode=True, enable_attributes=False)
    return HttpResponse(markup)

# vim: set ts=4 sw=4 et:

templates/news/add.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% block title %}BlackArch - News: {% if form.instance.id %}Edit{% else %}Add{% endif %} Article{% endblock %}

{% block content %}
<div id="news-add-article" class="box">

    {% if form.instance.id %}
    <h2>News: Edit Article</h2>
    {% else %}
    <h2>News: Add Article</h2>
    {% endif %}
    <p>News articles are formatted using
    <a href="http://daringfireball.net/projects/markdown/syntax">Markdown syntax</a>.
    Please use this syntax if at all possible over raw HTML, which can be used
    if Markdown doesn't support what you would like to do. Before posting, you
    are highly encouraged to use the <strong>Preview</strong> button to check
    your work.  Javascript must be enabled to use it, but it will render the
    news item exactly as it will appear on the news view page.</p>
    <form id="newsform" method="post">{% csrf_token %}
        <fieldset>
            {{ form.as_p }}
        </fieldset>
        <p>
        <label></label>
        <input title="Save changes" type="submit" value="Save" />
        <input id="news-preview-button" title="Preview" type="button" value="Preview" />
        </p>
    </form>
</div>

<div id="news-preview" class="news-article box" style="display:none;">
    <h2>News Preview: <span id="news-preview-title"></span></h2>
    <div id="news-preview-data" class="article-content"></div>
</div>
{% load cdn %}{% jquery %}
<script type="text/javascript" src="{% static "archweb.js" %}"></script>
<script type="text/javascript">
$(document).ready(enablePreview);
</script>
{% endblock %}

templates/news/delete.html
{% extends "base.html" %}
{% block title %}BlackArch - Delete News{% endblock %}

{% block content %}
<div id="news-delete-entry" class="box">

    <h2>News: Delete Entry Confirmation</h2>

    <p>You are about to delete the following news item:</p>

    <blockquote>
        <strong>{{news}}</strong>
    </blockquote>

    <p>Are you sure?</p>

    <form method="post">{% csrf_token %}
        <input title="Delete this article" id="delete" name="delete"
        type="submit" value="Delete" /></p>
    </form>

</div>
{% endblock %}

templates/news/list.html
{% extends "base.html" %}
{% load cycle from future %}

{% block title %}BlackArch - News{% endblock %}

{% block head %}
<link rel="alternate" type="application/rss+xml" title="BlackArch News Updates" href="/feeds/news/" />
{% endblock %}

{% block content %}
<div id="news-article-list" class="box">

    <h2>News Archives</h2>

    {% if perms.news.add_news %}
    <ul class="admin-actions">
        <li><a href="/news/add/" title="Add a news item">Add News Item</a></li>
    </ul>
    {% endif %}

    {% include "news/paginator.html" %}

    <table id="article-list" class="results">
        <thead>
            <tr>
                <th>Published</th>
                <th>Title</th>
                <th>Author</th>
                {% if perms.news.change_news %}
                <th></th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for item in news_list %}
            <tr class="{% cycle 'odd' 'even' %}">
                <td>{{ item.postdate|date }}</td>
                <td class="wrap"><a href="{{ item.get_absolute_url }}"
                        title="View: {{ item.title }}">{{ item.title }}</a></td>
                <td>{{ item.author.get_full_name }}</td>
                {% if perms.news.change_news %}
                <td>
                    <a href="{{ item.get_absolute_url }}edit/"
                        title="Edit: {{ item.title }}">Edit</a>
                    {% endif %}
                    {% if perms.news.delete_news %}
                    &nbsp;&nbsp;<a href="{{ item.get_absolute_url }}delete/"
                        title="Delete: {{ item.title }}">Delete</a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>

    {% include "news/paginator.html" %}

</div>
{% endblock %}

templates/news/paginator.html
{% if is_paginated %}
<div class="pagination">
    <p>{{ paginator.count }} news items, viewing page {{ page_obj.number }} of {{ paginator.num_pages }}.</p>
    <p class="news-nav">
    {% if page_obj.has_previous %}
    <a class="prev" href="?page={{ page_obj.previous_page_number }}"
        title="Go to previous page">&lt; Prev</a>
    {% endif %}
    {% for num in paginator.page_range %}
    {% ifequal num page_obj.number %}
    <span>{{ num }}</span>
    {% else %}
    <a href="?page={{ num }}" title="Go to page {{ num }}">{{ num }}</a>
    {% endifequal %}
    {% endfor %}
    {% if page_obj.has_next %}
    <a class="next" href="?page={{ page_obj.next_page_number }}"
        title="Go to next page">Next &gt;</a>
    {% endif %}
    </p>
</div>
{% endif %}

templates/news/view.html
{% extends "base.html" %}
{% block title %}BlackArch - News: {{ news.title }}{% endblock %}

{% block content %}
<div itemscope itemtype="http://schema.org/Article" class="news-article box">
    <h2 itemprop="headline">{{ news.title }}</h2>
    <meta itemprop="dateCreated" content="{{ news.postdate|date:"Y-m-d" }}"/>
    <meta itemprop="datePublished" content="{{ news.postdate|date:"Y-m-d" }}"/>
    <meta itemprop="dateModified" content="{{ news.last_modified|date:"Y-m-d" }}"/>
    <meta itemprop="inLanguage" content="en"/>
    <meta itemprop="wordCount" content="{{ news.content|wordcount }}"/>
    <div style="display:none" itemprop="author" itemscope itemtype="http://schema.org/Person">
        <meta itemprop="name" content="{{ news.author.get_full_name|escape }}"/>
    </div>
    <div style="display:none" itemprop="publisher" itemscope itemtype="http://schema.org/Organization">
        <meta itemprop="name" content="BlackArch"/>
    </div>

    {% if perms.news.change_news %}
    <ul class="admin-actions">
        <li><a href="edit/" title="Edit this article">Edit News Item</a></li>
        {% if perms.news.delete_news %}
        <li><a href="delete/" title="Delete this article">Delete News Item</a></li>
        {% endif %}
    </ul>
    {% endif %}

    <p class="article-info">{{ news.postdate|date }} - {{ news.author.get_full_name }}</p>

    <div class="article-content" itemprop="articleBody">{{ news.html }}</div>
</div>
{% endblock %}