releng/urls.py
from django.conf.urls import include, patterns

from .views import ReleaseListView, ReleaseDetailView

feedback_patterns = patterns('releng.views',
    (r'^$',                              'test_results_overview', {}, 'releng-test-overview'),
    (r'^submit/$',                       'submit_test_result', {}, 'releng-test-submit'),
    (r'^thanks/$',                       'submit_test_thanks', {}, 'releng-test-thanks'),
    (r'^iso/(?P<iso_id>\d+)/$',          'test_results_iso', {}, 'releng-results-iso'),
    (r'^(?P<option>.+)/(?P<value>\d+)/$','test_results_for', {}, 'releng-results-for'),
    (r'^iso/overview/$',                 'iso_overview', {}, 'releng-iso-overview'),
)

releases_patterns = patterns('releng.views',
    (r'^$',
        ReleaseListView.as_view(), {}, 'releng-release-list'),
    (r'^(?P<version>[-.\w]+)/$',
        ReleaseDetailView.as_view(), {}, 'releng-release-detail'),
    (r'^(?P<version>[-.\w]+)/torrent/$',
        'release_torrent', {}, 'releng-release-torrent'),
)

urlpatterns = patterns('',
    (r'^feedback/', include(feedback_patterns)),
    (r'^releases/', include(releases_patterns)),
)

# vim: set ts=4 sw=4 et:

urls.py
from django.conf.urls import include, patterns, url
from django.contrib import admin
from django.contrib.sitemaps import views as sitemap_views

from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView, RedirectView

from feeds import PackageFeed, NewsFeed, ReleaseFeed
import sitemaps

our_sitemaps = {
    'base':           sitemaps.BaseSitemap,
    'news':           sitemaps.NewsSitemap,
    'packages':       sitemaps.PackagesSitemap,
    'package-files':  sitemaps.PackageFilesSitemap,
    'package-groups': sitemaps.PackageGroupsSitemap,
    'split-packages': sitemaps.SplitPackagesSitemap,
    'releases':       sitemaps.ReleasesSitemap,
}

admin.autodiscover()
urlpatterns = []

# Public pages
urlpatterns += patterns('public.views',
    (r'^$', 'index', {}, 'index'),
    (r'^about/$', TemplateView.as_view(template_name='public/about.html'),
        {}, 'page-about'),
# Commented out as not used for BlackArchweb
#    (r'^art/$',   TemplateView.as_view(template_name='public/art.html'),
#        {}, 'page-art'),
#    (r'^svn/$',   TemplateView.as_view(template_name='public/svn.html'),
#        {}, 'page-svn'),
    (r'^developers/$',   'userlist', { 'user_type':'devs' },    'page-devs'),
#    (r'^trustedusers/$', 'userlist', { 'user_type':'tus' },     'page-tus'),
#    (r'^fellows/$',      'userlist', { 'user_type':'fellows' }, 'page-fellows'),
    (r'^donate/$',       'donate',   {}, 'page-donate'),
    (r'^download/$',     'download', {}, 'page-download'),
    (r'^master-keys/$',  'keys',     {}, 'page-keys'),
    (r'^master-keys/json/$', 'keys_json', {}, 'pgp-keys-json'),
)

# Feeds patterns, used below
feeds_patterns = patterns('',
    (r'^$',          'public.views.feeds', {}, 'feeds-list'),
    (r'^news/$',     cache_page(300)(NewsFeed())),
    (r'^packages/$', cache_page(300)(PackageFeed())),
    (r'^packages/(?P<arch>[A-z0-9]+)/$',
        cache_page(300)(PackageFeed())),
    (r'^packages/all/(?P<repo>[A-z0-9\-]+)/$',
        cache_page(300)(PackageFeed())),
    (r'^packages/(?P<arch>[A-z0-9]+)/(?P<repo>[A-z0-9\-]+)/$',
        cache_page(300)(PackageFeed())),
    (r'^releases/$', cache_page(300)(ReleaseFeed())),
)

# Includes and other remaining stuff
urlpatterns += patterns('',
    # cache this static JS resource for 1 week rather than default 5 minutes
    (r'^admin/',     include(admin.site.urls)),
    (r'^devel/',     include('devel.urls')),
    (r'^feeds/',     include(feeds_patterns)),
    (r'^groups/',    include('packages.urls_groups')),
    (r'^mirrorlist/',include('mirrors.urls_mirrorlist')),
    (r'^mirrors/',   include('mirrors.urls')),
    (r'^news/',      include('news.urls')),
    (r'^packages/',  include('packages.urls')),
    (r'^releng/',    include('releng.urls')),
    (r'^todo/',      include('todolists.urls')),
    (r'^visualize/', include('visualize.urls')),
    (r'^opensearch/packages/$', 'packages.views.opensearch',
        {}, 'opensearch-packages'),
    (r'^opensearch/packages/suggest$', 'packages.views.opensearch_suggest',
        {}, 'opensearch-packages-suggest'),
)

# Retro home page views
urlpatterns += patterns('retro.views',
    (r'^retro/(?P<year>[0-9]{4})/$', 'retro_homepage', {}, 'retro-homepage'),
)

# Sitemaps
urlpatterns += patterns('',
    (r'^sitemap.xml$',
        cache_page(1800)(sitemap_views.index),
        {'sitemaps': our_sitemaps, 'sitemap_url_name': 'sitemaps'}),
    (r'^sitemap-(?P<section>.+)\.xml$',
        cache_page(1800)(sitemap_views.sitemap),
        {'sitemaps': our_sitemaps}, 'sitemaps'),
)

# Authentication / Admin
urlpatterns += patterns('django.contrib.auth.views',
    (r'^login/$',           'login',  {
        'template_name': 'registration/login.html'}),
    (r'^logout/$',          'logout', {
        'template_name': 'registration/logout.html'}),
)

# Redirects for older known pages we see in the logs
legacy_urls = (
    ('^about.php',     '/about/'),
    ('^changelog.php', '/packages/?sort=-last_update'),
    ('^devs.php',      '/developers/'),
    ('^donations.php', '/donate/'),
    ('^download.php',  '/download/'),
    ('^index.php',     '/'),
    ('^logos.php',     '/art/'),
    ('^news.php',      '/news/'),
    ('^packages.php',  '/packages/'),
    ('^people.php',    '/developers/'),
    ('^todolists/$',   '/todo/'),

    ('^docs/en/guide/install/arch-install-guide.html',
        'https://wiki.archlinux.org/index.php/Installation_Guide'),
    ('^docs/en/',
        'https://wiki.archlinux.org/'),
    ('^docs/',
        'https://wiki.archlinux.org/'),
)

urlpatterns += [url(old_url, RedirectView.as_view(url=new_url))
        for old_url, new_url in legacy_urls]


def show_urls(urllist=urlpatterns, depth=0):
    for entry in urllist:
        print "  " * depth, entry.regex.pattern
        if hasattr(entry, 'url_patterns'):
            show_urls(entry.url_patterns, depth + 1)

# vim: set ts=4 sw=4 et:

releng/models.py
from base64 import b64decode
from bencode import bdecode, bencode
from datetime import datetime
import hashlib
import markdown
from pytz import utc

from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import pre_save
from django.utils.safestring import mark_safe

from main.fields import PositiveBigIntegerField
from main.utils import set_created_field


class IsoOption(models.Model):
    name = models.CharField(max_length=200)

    def __unicode__(self):
        return self.name

    class Meta:
        abstract = True


class RollbackOption(IsoOption):
    class Meta:
        abstract = True


class Iso(models.Model):
    name = models.CharField(max_length=255)
    created = models.DateTimeField(editable=False)
    removed = models.DateTimeField(null=True, blank=True, default=None)
    active = models.BooleanField(default=True)

    def get_absolute_url(self):
        return reverse('releng-results-iso', args=[self.pk])

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = 'ISO'


class Architecture(IsoOption):
    pass


class IsoType(IsoOption):
    class Meta:
        verbose_name = 'ISO type'


class BootType(IsoOption):
    pass


class HardwareType(IsoOption):
    pass


class InstallType(IsoOption):
    pass


class Source(IsoOption):
    pass


class ClockChoice(IsoOption):
    pass


class Filesystem(RollbackOption):
    pass


class Module(RollbackOption):
    pass


class Bootloader(IsoOption):
    pass


class Test(models.Model):
    user_name = models.CharField(max_length=500)
    user_email = models.EmailField('email address')
    # Great work, Django... https://code.djangoproject.com/ticket/18212
    ip_address = models.GenericIPAddressField(verbose_name='IP address',
            unpack_ipv4=True)
    created = models.DateTimeField(editable=False)

    iso = models.ForeignKey(Iso)
    architecture = models.ForeignKey(Architecture)
    iso_type = models.ForeignKey(IsoType)
    boot_type = models.ForeignKey(BootType)
    hardware_type = models.ForeignKey(HardwareType)
    install_type = models.ForeignKey(InstallType)
    source = models.ForeignKey(Source)
    clock_choice = models.ForeignKey(ClockChoice)
    filesystem = models.ForeignKey(Filesystem)
    modules = models.ManyToManyField(Module, null=True, blank=True)
    bootloader = models.ForeignKey(Bootloader)
    rollback_filesystem = models.ForeignKey(Filesystem,
            related_name="rollback_test_set", null=True, blank=True)
    rollback_modules = models.ManyToManyField(Module,
            related_name="rollback_test_set", null=True, blank=True)

    success = models.BooleanField()
    comments = models.TextField(null=True, blank=True)


class Release(models.Model):
    release_date = models.DateField(db_index=True)
    version = models.CharField(max_length=50, unique=True)
    kernel_version = models.CharField(max_length=50, blank=True)
    torrent_infohash = models.CharField(max_length=40, blank=True)
    md5_sum = models.CharField('MD5 digest', max_length=32, blank=True)
    sha1_sum = models.CharField('SHA1 digest', max_length=40, blank=True)
    file_size = PositiveBigIntegerField(null=True, blank=True)
    created = models.DateTimeField(editable=False)
    available = models.BooleanField(default=True)
    info = models.TextField('Public information', blank=True)
    torrent_data = models.TextField(blank=True)

    class Meta:
        get_latest_by = 'release_date'
        ordering = ('-release_date', '-version')

    def __unicode__(self):
        return self.version

    def get_absolute_url(self):
        return reverse('releng-release-detail', args=[self.version])

    def dir_path(self):
        return "iso/%s/" % self.version

    def iso_url(self):
        return "iso/%s/archlinux-%s-dual.iso" % (self.version, self.version)

    def magnet_uri(self):
        query = [
            ('dn', "archlinux-%s-dual.iso" % self.version),
        ]
        if settings.TORRENT_TRACKERS:
            query.extend(('tr', uri) for uri in settings.TORRENT_TRACKERS)
        if self.torrent_infohash:
            query.insert(0, ('xt', "urn:btih:%s" % self.torrent_infohash))
        return "magnet:?%s" % '&'.join(['%s=%s' % (k, v) for k, v in query])

    def info_html(self):
        return mark_safe(markdown.markdown(
            self.info, safe_mode=True, enable_attributes=False))

    def torrent(self):
        try:
            data = b64decode(self.torrent_data.encode('utf-8'))
        except TypeError:
            return None
        if not data:
            return None
        data = bdecode(data)
        # transform the data into a template-friendly dict
        info = data.get('info', {})
        metadata = {
            'comment': data.get('comment', None),
            'created_by': data.get('created by', None),
            'creation_date': None,
            'announce': data.get('announce', None),
            'file_name': info.get('name', None),
            'file_length': info.get('length', None),
            'piece_count': len(info.get('pieces', '')) / 20,
            'piece_length': info.get('piece length', None),
            'url_list': data.get('url-list', []),
            'info_hash': None,
        }
        if 'creation date' in data:
            created= datetime.utcfromtimestamp(data['creation date'])
            metadata['creation_date'] = created.replace(tzinfo=utc)
        if info:
            metadata['info_hash'] = hashlib.sha1(bencode(info)).hexdigest()

        return metadata


for model in (Iso, Test, Release):
    pre_save.connect(set_created_field, sender=model,
            dispatch_uid="releng.models")

# vim: set ts=4 sw=4 et:

templates/releng/add.html
{% extends "base.html" %}

{% block title %}BlackArch - Test Result Entry{% endblock %}

{% block content %}
<div class="box">
    <h2>Arch Releng Testbuild Feedback Entry</h2>

    <p>This page allows you to submit feedback after testing an BlackArch installation
    using a release engineering testbuild.  Mark all the options you used during the
    installation; at the end you can specify whether everything went OK.  Be
    sure to only denote a successful install after having checked the
    installation properly.  Some options require you to check several things (such as
    config files), this will be mentioned alongside the option.</p>
    <p>There is also an overview of all feedback on the
    <a href="{% url 'releng-test-overview' %}">results page</a>.  Once we have
    builds that are properly tested (enough successful feedback for all
    important features of the ISO or a slightly earlier ISO), we can release new
    official media.</p>

    <div id="releng-feedback"> <form action="" method="post">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Submit" />
        </form>
    </div>
</div>
{% endblock %}

templates/releng/iso_overview.html
{% extends "base.html" %}
{% load static from staticfiles %}

{% block content %}
<div class="box">
    <h2>Failures and Successes for Testing ISOs</h2>

    <p>This is an overview showing all current or tested release engineering
    produced ISOs. Past but now unavailable ISOs are ommitted if there were
    never any testing results submitted. To help improve ISO quality, you are
    encouraged to <a href="{% url 'releng-test-submit' %}">give feedback</a>
    if you have tested and used any ISOs. Both successful and failed results
    are encouraged and welcome.</p>
    <p><a href="{% url 'releng-test-overview' %}">Go back to testing results</a></p>

    <table id="releng-result" class="results">
        <thead>
            <tr>
                <th>ISO</th>
                <th>Currently Available</th>
                <th># Successes</th>
                <th># Failures</th>
            </tr>
        </thead>
        <tbody>
            {% for iso in isos %}
            <tr>
                <td>
                    <a href="{{ iso.get_absolute_url }}">{{ iso.name }}</a>
                </td>
                <td>{{ iso.active|yesno|capfirst }}</td>
                <td>{{ iso.successes }}</td>
                <td>{{ iso.failures }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

{% block script_block %}
{% load cdn %}{% jquery %}{% jquery_tablesorter %}
<script type="text/javascript" src="{% static "archweb.js" %}"></script>
<script type="text/javascript">
$(document).ready(function() {
    $(".results:not(:has(tbody tr.empty))").tablesorter({widgets: ['zebra']});
});
</script>
{% endblock %}

templates/releng/release_detail.html
{% extends "base.html" %}

{% block title %}BlackArch - Release: {{ release.version }}{% endblock %}

{% block content %}
<div class="release box">
    <h2>{{ release.version }}</h2>

    <ul>
        <li><strong>Release Date:</strong> {{ release.release_date|date }}</li>
        {% if release.kernel_version %}<li><strong>Kernel Version:</strong> {{ release.kernel_version }}</li>{% endif %}
        <li><strong>Available:</strong> {{ release.available|yesno }}</li>
        {% if release.available %}<li><strong>Download:</strong> <a
                href="{% url 'releng-release-torrent' release.version %}"
                title="Download torrent for {{ release.version }}">Torrent</a>,
            <a href="{{ release.magnet_uri }}">Magnet</a></li>{% endif %}
        {% if release.torrent_infohash %}<li><strong>Torrent Info Hash:</strong> {{ release.torrent_infohash }}</li>{% endif %}
        {% if release.md5_sum %}<li><strong>MD5:</strong> {{ release.md5_sum }}</li>{% endif %}
        {% if release.sha1_sum %}<li><strong>SHA1:</strong> {{ release.sha1_sum }}</li>{% endif %}
        <li><strong>Download Size:</strong> {% if release.file_size %}{{ release.file_size|filesizeformat }}{% else %}Unknown{% endif %}</li>
    </ul>

    {% if release.info %}
    <h3>Release Notes</h3>

    <div class="article-content">{{ release.info_html }}</div>
    {% endif %}

    {% if release.torrent_data %}{% with release.torrent as torrent %}
    <h3>Torrent Information</h3>

    <ul>
        <li><strong>Comment:</strong> {{ torrent.comment }}</li>
        <li><strong>Creation Date:</strong> {{ torrent.creation_date|date:"DATETIME_FORMAT" }} UTC</li>
        <li><strong>Created By:</strong> {{ torrent.created_by }}</li>
        <li><strong>Announce URL:</strong> {{ torrent.announce }}</li>
        <li><strong>File Name:</strong> {{ torrent.file_name }}</li>
        <li><strong>File Length:</strong> {{ torrent.file_length|filesizeformat }}</li>
        <li><strong>Piece Count:</strong> {{ torrent.piece_count }} pieces</li>
        <li><strong>Piece Length:</strong> {{ torrent.piece_length|filesizeformat }}</li>
        <li><strong>Computed Info Hash:</strong> {{ torrent.info_hash }}</li>
        <li><strong>URL List Length:</strong> {{ torrent.url_list|length }} URLs</li>
    </ul>
    {% endwith %}{% endif %}
</div>
{% endblock %}

templates/releng/release_list.html
{% extends "base.html" %}
{% load cycle from future %}
{% load static from staticfiles %}

{% block title %}BlackArch - Releases{% endblock %}

{% block head %}
<link rel="alternate" type="application/rss+xml" title="BlackArch News Updates" href="/feeds/releases/" />
{% endblock %}

{% block content %}
<div id="release-list" class="box">
    <h2>Releases</h2>

    <table id="release-table" class="results">
        <thead>
            <tr>
                <th>Release Date</th>
                <th>Version</th>
                <th>Kernel Version</th>
                <th>Available?</th>
                <th>Torrent</th>
                <th>Magnet</th>
                <th>Download Size</th>
            </tr>
        </thead>
        <tbody>
            {% for item in release_list %}
            <tr class="{% cycle 'odd' 'even' %}">
                <td>{{ item.release_date|date }}</td>
                <td><a href="{{ item.get_absolute_url }}" title="Release details for {{ item.version }}">{{ item.version }}</a></td>
                <td>{{ item.kernel_version|default:"" }}</td>
                <td class="available-{{ item.available|yesno }}">{{ item.available|yesno|capfirst }}</td>
                <td>{% if item.available %}<a href="{% url 'releng-release-torrent' item.version %}"
                        title="Download torrent for {{ item.version }}">Torrent</a>{% endif %}</td>
                <td>{% if item.available %}<a href="{{ item.magnet_uri }}">Magnet</a>{% endif %}</td>
                <td>{% if item.file_size %}{{ item.file_size|filesizeformat }}{% endif %}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

{% block script_block %}
{% load cdn %}{% jquery %}{% jquery_tablesorter %}
<script type="text/javascript" src="{% static "archweb.js" %}"></script>
<script type="text/javascript">
$(document).ready(function() {
    $(".results").tablesorter({
        widgets: ['zebra'],
        sortList: [[0,1], [1,1]],
        headers: { 4: { sorter: false }, 5: { sorter: false } }
    });
});
</script>
{% endblock %}

templates/releng/result_list.html
{% extends "base.html" %}
{% load static from staticfiles %}

{% block content %}
<div class="box">
    <h2>Results for:
        {% if option %}{{ option.verbose_name|title }}: {{ value }}{% endif %}
        {% if iso_name %}{{ iso_name|default:"" }}{% endif %}
    </h2>

    <p><a href="{% url 'releng-test-overview' %}">Go back to testing results</a></p>

    <table id="releng-result" class="results">
        <thead>
            <tr>
                <th>ISO</th>
                <th>Submitted By</th>
                <th>Date Submitted</th>
                <th>Architecture</th>
                <th>Success</th>
            </tr>
        </thead>
        <tbody>
            {% for test in test_list %}
            <tr>
                <td>{{ test.iso.name }}</td>
                <td>{{ test.user_name }}</td>
                <td>{{ test.created|date }}</td>
                <td>{{ test.architecture }}</td>
                <td><span class="success-{{ test.success|yesno }}">{{ test.success|yesno|capfirst }}</span></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

{% block script_block %}
{% load cdn %}{% jquery %}{% jquery_tablesorter %}
<script type="text/javascript" src="{% static "archweb.js" %}"></script>
<script type="text/javascript">
$(document).ready(function() {
    $(".results:not(:has(tbody tr.empty))").tablesorter({widgets: ['zebra']});
});
</script>
{% endblock %}

templates/releng/result_section.html
<tr>
    <th>{% if option.is_rollback %}Rollback: {% endif %}{{ option.name|title }}</th>
    <th>Last Success</th>
    <th>Last Failure</th>
</tr>
{% for item in option.values %}
<tr>
    <td>
        <a href="{% url 'releng-results-for' option.field_name item.value.pk %}">
            {{ item.value.name|lower }}
        </a>
    </td>
    <td>
        {% if item.success %}
        <a href="{% url 'releng-results-iso' item.success.pk %}">
            {{ item.success.name }}
        </a>
        {% else %}Never succeeded{% endif %}
    </td>
    <td>
        {% if item.failure %}
        <a href="{% url 'releng-results-iso' item.failure.pk %}">
            {{ item.failure.name }}
        </a>
        {% else %}Never failed{% endif %}
    </td>
</tr>
{% endfor %}

templates/releng/results.html
{% extends "base.html" %}

{% block title %}BlackArch - Release Engineering Testbuild Results{% endblock %}

{% block content %}
<div class="box">
    <h2>Release Engineering Testbuild Results</h2>

    <p>This is an overview showing a test results matrix of release
    engineering produced ISOs. Various options and configurations are shown
    with last success and last failure results, if known. To help improve ISO
    quality, you are encouraged to <a href="{% url 'releng-test-submit' %}">give feedback</a>
    if you have tested and used any ISOs. Both successful and failed results
    are encouraged and welcome.</p>

    <p>For a overview of which ISOs tested best, have a look at
    the <a href="{% url 'releng-iso-overview' %}">overview</a>.</p>

    <p>For more information, see the <a
    href="https://wiki.archlinux.org/index.php/DeveloperWiki:releng_testimages_feedback">documentation
    on the wiki</a>.</p>

    <p>All ISOs referenced on this page are available from
    <a href="{{ iso_url }}">{{ iso_url }}</a>.</p>

    <table>
        {% for option in options %}
        {% include "releng/result_section.html" %}
        {% endfor %}
    </table>
</div>
{% endblock %}

templates/releng/thanks.html
{% extends "base.html" %}

{% block title %}BlackArch - Feedback - Thanks!{% endblock %}

{% block content %}
<div class="box">
    <h2>Thanks!</h2>
    <p>Thank you for taking the time to give us this information!
    Your results have been succesfully added to our database.</p>
    <p>You can now <a href="{% url 'releng-test-overview' %}">go back to the results</a>,
    <a href="{% url 'releng-test-submit' %}">give more feedback</a>, or
    have a look at the <a href="{% url 'releng-iso-overview' %}">look at
    the ISO test overview</a>.</p>
</div>
{% endblock %}